name: notificar
description: "A new Flutter project."

publish_to: 'none' # Remove esta linha se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  shared_preferences: ^2.2.2
  firebase_messaging: 15.2.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3  # Moveu para dev_dependencies

flutter:
  uses-material-design: true

  # Adicionando os assets (imagens) utilizados no projeto
  assets:
    - assets/images/icone-notificar.png
    - assets/images/top_icon.png
    - assets/images/about_icon.png
    - assets/images/car_icon.png
    - assets/images/extra_icon.png
    - assets/images/profile_icon.png
    - assets/images/request_icon.png
    - assets/images/app_logo.png
    - assets/images/car_icon2.png
    - assets/images/plate_icon.png
    - assets/images/razao.png
    - assets/images/placa.png
    - assets/images/logo_grande.png

# Configuração do flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"  # Altere para o ícone correto
  adaptive_icon_foreground: "assets/images/app_logo.png"
  adaptive_icon_background: "#ffffff"  # Apenas para Android
